image: python:3.10

# this job must be called 'pages' to advise GitLab to upload content to GitLab Pages
pages:
  tags:
    - igs
  script:
    - pip install mkdocs-material
    - pip install mkdocs-include-markdown-plugin
    - pip install mkdocstrings
    - pip install mkdocstrings-python
    - pip install mkdocs-git-revision-date-localized-plugin
    - pip install mkdocs-open-in-new-tab
    # - mkdir -p public/en
    - mkdocs build -f config/en/mkdocs.yml --site-dir public/
  artifacts:
    paths:
      - public
  only: 
    - main
