image: python:3.10

# this job must be called 'pages' to advise GitLab to upload content to GitLab Pages
pages:
  stage: deploy
  tags:
    - igs
  script:
    - pip install --upgrade pip
    - pip install pymdown-extensions
    - pip install mkdocs-material
    - pip install mkdocs-material-extensions
    - pip install mkdocs-include-markdown-plugin
    - pip install mkdocstrings
    - pip install mkdocstrings-python
    - pip install mkdocs-git-revision-date-localized-plugin
    - pip install mkdocs-open-in-new-tab
    # - mkdir -p public/en
    - mkdocs build -f config/en/mkdocs.yml
    - mkdocs build -f config/de/mkdocs.yml
    - mkdocs build -f config/fr/mkdocs.yml
    - mkdocs build -f config/cn/mkdocs.yml
    - mv generated public
    # - ln -s public/en public
  artifacts:
    paths:
      - public
  only: 
    - main
