site_name: IGS CORS Guidelines
#site_url: https://igs.git-pages.gfz-potsdam.de/igs-cors-guidelines
repo_url: https://github.com/International-GNSS-Service/IGS_CORS_Guidelines
repo_name: IGS_CORS_Guidelines
copyright: Copyright &copy; 2024 International GNSS Service

docs_dir: '../../docs/en'
site_dir: '../../generated/en' 

nav:
  - Introduction: index.md
  - Summary: summary.md
  - Establishment and Operation:
    - Overview: establishment/index.md
    - Signal Quality: establishment/signals.md
    - Site Stability: establishment/stability.md
    - Power and Communications: establishment/power_comms.md
  - GNSS Equipment:
    - Overview: equipment/index.md
    - GNSS Receiver: equipment/receiver.md
    - GNSS Antenna: equipment/antenna.md
    - Antenna Cable: equipment/cable.md
    - Meteorological Sensors: equipment/meteo_sensors.md
  - Data and Metadata:
    - Overview: data/index.md
    - Signal Tracking and Data Recording: data/recording.md
    - File Naming Conventions: data/filename.md
    - Data Quality: data/quality.md
    - Metadata: data/metadata.md
    - Announcements: data/announcements.md
  - Resources:
    - Changelog: resources/changelog.md
    - Terms and Definitions: resources/terms.md
    - References: resources/references.md
    - Contributions: resources/contributions.md

theme:
  name: material
  language: en
  custom_dir: '../../overrides/' 
  logo: assets/images/igs_logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - def_list
  - toc:
      baselevel: 2
      permalink: true
  - meta
  - tables
  - footnotes
  - abbr
plugins:
  - include-markdown
  - search:
      lang: en
  - open-in-new-tab
  - git-revision-date-localized:
      enabled: true
      fallback_to_build_date: true
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/igsorg
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/igsorg
      name: X
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/igsorg
      name: Youtube
    - icon: material/email
      link: "mailto:cb@igs.org"

  alternate:
    - name: English
      link: /igs-cors-guidelines/en/ 
      lang: en
    - name: Deutsch
      link: /igs-cors-guidelines/de/
      lang: de
    - name: Français
      link: /igs-cors-guidelines/fr/
      lang: fr
    - name: 中国
      link: /igs-cors-guidelines/cn/ 
      lang: zh
