site_name: IGS CORS Guidelines
site_url: https://international-gnss-service.github.io/IGS_CORS_Guidelines/
repo_url: https://github.com/International-GNSS-Service/IGS_CORS_Guidelines
repo_name: IGS_CORS_Guidelines
copyright: Copyright &copy; 2024 International GNSS Service

docs_dir: ../../docs/en   # points to your English Markdown files
# site_dir is REMOVED — workflow will control output

nav:
  - Introduction: index.md
  - Summary: summary.md
  - Establishment and Operation:
      - Overview: establishment/index.md
      - Signal Quality: establishment/signals.md
      - Site Stability: establishment/stability.md
      - Power and Communications: establishment/power_comms.md
  - GNSS Equipment:
      - Overview: equipment/index.md
      - GNSS Receiver: equipment/receiver.md
      - GNSS Antenna: equipment/antenna.md
      - Antenna Cable: equipment/cable.md
      - Meteorological Sensors: equipment/meteo_sensors.md
  - Data and Metadata:
      - Overview: data/index.md
      - Signal Tracking and Data Recording: data/recording.md
      - File Naming Conventions: data/filename.md
      - Data Quality: data/quality.md
      - Metadata: data/metadata.md
      - Announcements: data/announcements.md

theme:
  name: material
  language: en
  custom_dir: ../../overrides/
  logo: assets/images/igs_logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
    - scheme: default
      primary: blue
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - toc.follow
markdown_extensions:
  - admonition
  - toc:
      baselevel: 2
      permalink: true
plugins:
  - search:
      lang: en
