site_name: IGS CORS Guidelines
site_url: https://igs.git-pages.gfz-potsdam.de/igs-cors-guidelines
repo_url: https://git.gfz-potsdam.de/igs/igs-cors-guidelines
repo_name: igs/igs-cors-guidelines
copyright: Copyright &copy; 2024 International GNSS Service

docs_dir: '../../docs/de'
site_dir: '../../generated/de' 

nav:
  - Einleitung: index.md
  - Zusammenfassung: summary.md
  - Aufbau und Betrieb:
    - Übersicht: establishment/index.md
    - Signalqualität: establishment/signals.md
    - Stabilität: establishment/stability.md
    - Strom und Kommunikation: establishment/power_comms.md
  - GNSS Equipment:
    - Übersicht: equipment/index.md
    - GNSS Empfänger: equipment/receiver.md
    - GNSS Antennen: equipment/antenna.md
    - Antennenkabel: equipment/cable.md
    - Meteorologische Sensoren: equipment/meteo_sensors.md
  - Daten und Metadaten:
    - Übersicht: data/index.md
    - Signal- und Datenaufzeichnung: data/recording.md
    - Dateinamenkonventionen: data/filename.md
    - Datenqualität: data/quality.md
    - Metadaten: data/metadata.md
    - Ankündigungen: data/announcements.md
  - Ressourcen:
    - Changelog: resources/changelog.md
    - Definitionen: resources/terms.md
    - Referenzen: resources/references.md
    - Beitrag: resources/contributions.md

theme:
  name: material
  language: de
  custom_dir: '../../overrides/' 
  logo: assets/images/igs_logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - def_list
  - toc:
      baselevel: 2
      permalink: true
  - meta
  - tables
  - footnotes
  - abbr
plugins:
  - include-markdown
  - search:
      lang: de
  - open-in-new-tab
  - git-revision-date-localized:
      enable_creation_date: true
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://git.gfz-potsdam.de/igs/igs-cors-guidelines
      name: GitLab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/igsorg
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/igsorg
      name: X
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/igsorg
      name: Youtube
    - icon: material/email
      link: "mailto:cb@igs.org"

  alternate:
    - name: English
      link: /igs-cors-guidelines/en/ 
      lang: en
    - name: Deutsch
      link: /igs-cors-guidelines/de/
      lang: de
    - name: Français
      link: /igs-cors-guidelines/fr/
      lang: fr
    - name: 中国
      link: /igs-cors-guidelines/cn/ 
      lang: zh